# docker build -t alvinlucillo/k8todo-frontend -f ./Dockerfile ./

# docker pull mongo:latest
# docker run -d -p 3002:27017 --name k8todo-db mongo:latest

#  docker ps -a --filter "name=k8todo-frontend" 